name: Checks

on: push

jobs:

  basic_tests:
    name: Basic Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Resume cache
        uses: actions/cache@v2
        id: cache-workflow-dependencies
        with:
          path: |
            ~/.cache/apt-pkg-cache
          key: ${{ runner.os }}-build-${{ hashFiles('.github/workflows/basic_tests.yml') }}

      - name: Install dependencies
        env:
          CACHE_HIT: ${{steps.cache-workflow-dependencies.outputs.cache-hit}}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            echo "Using cached apt and pip packages"
            sudo cp -rf ~/.cache/apt-pkg-cache/* /
          else
            sudo apt-get update
            sudo apt-get install python3-tk
            mkdir -p ~/.cache/apt-pkg-cache
            for dep in blt python3-tk tk8.6-blt2.5; do
              dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/.cache/apt-pkg-cache
            done
          fi

      - name: Running unittests
        timeout-minutes: 2
        run: python3 tests.py
